[2] create db
epitaphprince/cesp-database pull request #4
Opened 2019-03-03 14:31 UTC by InnaStarchenkova

2019-03-03 14:57 UTC, gamefreakru requested changes

2019-03-03 14:57 UTC, epitaphprince commented on Centroespanol.Database/Centroespanol.Database.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Centroespanol.Database", "Centroespanol.Database\Centroespanol.Database.csproj", "{22641AEE-1F77-4780-8B76-36C0836A98CF}"
Давай писать CESP вместо centroespanol.

2019-03-03 14:57 UTC, epitaphprince commented on Centroespanol.Database/Centroespanol.Database/Centroespanol.Database.csproj
> +        <TargetFramework>netcoreapp2.1</TargetFramework>
2.2

2019-03-03 14:57 UTC, epitaphprince commented on Centroespanol.Database/Centroespanol.Database/Context/CentroespanolContextFactory.cs
> +            var supplierConnectionString = config
Почему supplier?)

2019-03-03 15:02 UTC, InnaStarchenkova commented on Centroespanol.Database/Centroespanol.Database/Context/CentroespanolContextFactory.cs
> +            var supplierConnectionString = config
ctrl-v подвел)

2019-03-03 15:48 UTC, InnaStarchenkova commented on Centroespanol.Database/Centroespanol.Database.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Centroespanol.Database", "Centroespanol.Database\Centroespanol.Database.csproj", "{22641AEE-1F77-4780-8B76-36C0836A98CF}"
исправила

2019-03-03 15:48 UTC, InnaStarchenkova commented on Centroespanol.Database/Centroespanol.Database/Centroespanol.Database.csproj
> +        <TargetFramework>netcoreapp2.1</TargetFramework>
исправила

2019-03-03 15:48 UTC, InnaStarchenkova commented on Centroespanol.Database/Centroespanol.Database/Context/CentroespanolContextFactory.cs
> +            var supplierConnectionString = config
исправила

2019-03-05 07:01 UTC, gamefreakru approved these changes

2019-03-05 07:02 UTC, merged